# Generated by Django 2.2.1 on 2020-02-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='webshopApp.Cart'),
            preserve_default=False,
        ),
    ]
