# Generated by Django 2.2.1 on 2020-02-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshopApp', '0003_remove_purchase_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='security_number',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshopApp.Item')),
            ],
        ),
    ]
