# Generated by Django 2.2.1 on 2020-02-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopApp', '0008_auto_20200202_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
