# Generated by Django 2.2.1 on 2020-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopApp', '0009_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_link',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paying',
            field=models.CharField(default='', max_length=4),
        ),
    ]
